name: Build base

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'ubuntu.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        forge: [mamba, conda]
        include:
          - forge: mamba
            miniforge: Mambaforge
          - forge: conda
            miniforge: Miniforge3
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ubuntu.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{matrix.forge}}
          build-args: |
            MINIFORGE=${{matrix.miniforge}}